---
title: LabQuiz demo
subtitle: demo
#doi: 10.14288/1.0362383
date: 02/12/2026
license: CC-BY-NC-SA-4.0
authors:
  - name: Jean-François Bercher
    email: jf.bercher@esiee.fr
    url: https://perso.esiee.fr/~bercherj/
    corresponding: true
    orcid: 0009-0007-5474-7475
    affiliations:
      - name: LIGM
        url: https://ligm.univ-eiffel.fr/
      - name: Dept IT, ESIEE
settings:
    myst_to_tex:
        code_style: listings
    output_stderr: remove
    output_matplotlib_strings: remove
exports:
  - format: docx
  - format: pdf
    template: arxiv_nips
    article_type: article
    chapters: []
numbering:
  title: 
    enabled: true
    offset: 0
  heading_1: true
  heading_2: true
  heading_3: true
math:
  '\sha': 'ш'
  '\dr': '\mathrm{d}#1'
  '\wb': '\mathbf{w}'
  '\tf': '\mathrm{FT}\left\{#1\right\}'
  '\flecheTF': '\rightleftharpoons'
  '\TFI': '\displaystyle{\int_{-\infty}^{+\infty} #1 \, e^{j2\pi #2 #3} \, \dr{#2}}'
  '\TF': '\displaystyle{\int_{-\infty}^{+\infty} #1 \, e^{-j2\pi #3 #2} \, \dr{#2}}'
  '\ttt': '\mathbf{v}'
  '\myblueeqbox': '{\fcolorbox{blue}{lightblue}{\textcolor{blue}{#1}}}'
  '\myeqbox': '{\fcolorbox{#1}{light#1}{\textcolor{#1}{#2}}}'
  '\eqbox': '{\fcolorbox{#1}{#2}{\textcolor{#3}{$#4$}}}'
  '\eqboxa': '{\boxed{#1}}'
  '\eqboxb': '{\eqbox{green}{white}{green}{#1}}'
  '\eqboxc': '{\eqbox{blue}{white}{blue}{#1}}'
  '\eqboxd': '{\eqbox{blue}{white}{blue}{#1}}' #lightblue
  '\E': '{\mathbb{E}\left#1\right}'
  '\ta': '{\left<#1\right>}'
  '\egalparerg': '{\mathop{=}\limits_{\mathrm{erg}}}'
  '\expo': '\exp\left(#1\right)'
  '\d': '\mathrm{d}#1'
  '\sb': '\mathbf{s}'
  '\xb': '\mathbf{x}'
  '\yb': '\mathbf{y}'
  '\Xb': '\mathbf{X}'
  '\Rb': '\mathbf{R}'
  '\rb': '\mathbf{r}'
  '\mystar': '{*}'
  '\ub': '\mathbf{u}'
  '\wbopt': '{\mathop{\mathbf{w}}\limits^{\triangle}}'
  '\deriv': '\frac{\mathrm{d}#1}{\mathrm{d}#2}'
  '\Ub': '\mathbf{U}'
  '\db': '\mathbf{d}'
  '\eb': '\mathbf{e}'
  '\vb': '\mathbf{v}'
  '\Ib': '\mathbf{I}'
  '\Vb': '\mathbf{V}'
  '\betab': '\boldsymbol{\beta}'
  '\Lambdab': '\mathbf{\Lambda}'
  '\Ab': '\mathbf{A}'
  '\Bb': '\mathbf{B}'
  '\Cb': '\mathbf{C}'
  '\Db': '\mathbf{D}'
  '\Kb': '\mathbf{K}'
---

```{note} In case of version or data issues
 - ``*hard*'' reloading: depending on the browser Ctrl + Shift + R, Shift+⌘+R, Ctrl + F5
 - Clear cache and cookies: Search for “Delete (or erase) browsing data”
      - Brave: Brave menu at the top left or Shift+⌘+⌫ 
 - Empty the DB index - F12 key to access the professional options, Application/Storage/Clear site data menu
```

```{note} Run cells
To run the cells: “Run” menu 
or: 
- Windows/Linux CTRL-Enter (simple execution), ALT-Enter (executes and inserts a cell below)
- Mac ⌘-Enter (simple execution), ⌥-Enter (executes and inserts a cell below)
```

```{hint} Table of contents
To display a table of contents, press the table of contents button on the left; or `View/Table of Contents` menu
```

```{warning}
Run the cell below!
```

In [ ]:
LABQUIZ_LAST_VERSION = "0.7.9.1"
labquiz_url = f"https://perso.esiee.fr/~bercherj/JliteNotes/pypi/labquiz-{LABQUIZ_LAST_VERSION}-py3-none-any.whl"
import sys
if sys.platform == "emscripten":   #Jupyterlite
    import micropip
    import js
    from jfb_jlite_init import get_base_url, setup_env, update_files
    import pyodide_http
    base_url = get_base_url()
    toinstall = [labquiz_url, 'requests', 'ipywidgets', 'cryptography', 'pandas', 'statsmodels']
    print(f"📍 Serveur détecté : {base_url}")
    print(f"📦 Cible : {labquiz_url}")
    print("💡 Installation of required packages")
    print("   --------------------------------")
    await setup_env(base_url, toinstall)
    print("\n💡 Udating data files")
    await update_files(toinstall)
else:
# Latest version can be found in https://github.com/jfbercher/labquiz/releases    print("💡 Installation of required packages (classical Python)")
# Put them here...    print(f"👉 Installing labquiz package, version: {LABQUIZ_LAST_VERSION}...")
    %pip install "https://perso.esiee.fr/~bercherj/JliteNotes/pypi/labquiz-{LABQUIZ_LAST_VERSION}-py3-none-any.whl" --upgrade -qq
    print("✅ Successful install.")

In [1]:
%load_ext autoreload
%autoreload 2

In [19]:
#%pip install git+https://github.com/jfbercher/labquiz.git

Collecting git+https://github.com/jfbercher/labquiz.git
  Cloning https://github.com/jfbercher/labquiz.git to /private/var/folders/y4/_fmvp6f90fz8qzbxtlfl6pwr0000gn/T/pip-req-build-gcxclh_o
  Running command git clone --filter=blob:none --quiet https://github.com/jfbercher/labquiz.git /private/var/folders/y4/_fmvp6f90fz8qzbxtlfl6pwr0000gn/T/pip-req-build-gcxclh_o
  Resolved https://github.com/jfbercher/labquiz.git to commit bc5ef5f735e4a7520ae0f137905390f7bceaa91b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: ipywidgets>=7.6.5 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.6) (8.1.8)
Requirement already satisfied: pyyaml in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.6) (6.0.3)
Requirement already satisfied: cryptography in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.6) (46.0.5)
Requirement already satisfied: ipython in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.6) (8.18.1)
Requirement already satisfied: numpy in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.6) (2.0.2)
Requirement already satisfied: pandas in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.6) (2.3.3)
Requirement already satisfied: requests in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.6) (2.32.5)
Requirement already satisfied: comm>=0.1.3 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets>=7.6.5->labquiz==0.8.6) (0.2.3)
Requirement already satisfied: traitlets>=4.3.1 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets>=7.6.5->labquiz==0.8.6) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets>=7.6.5->labquiz==0.8.6) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets>=7.6.5->labquiz==0.8.6) (3.0.16)
Requirement already satisfied: decorator in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.6) (5.2.1)
Requirement already satisfied: jedi>=0.16 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.6) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.6) (0.2.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.6) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.6) (2.19.2)
Requirement already satisfied: stack-data in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.6) (0.6.3)
Requirement already satisfied: typing-extensions in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.6) (4.15.0)
Requirement already satisfied: exceptiongroup in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.6) (1.3.1)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.6) (4.9.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->labquiz==0.8.6) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from jedi>=0.16->ipython->labquiz==0.8.6) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from pexpect>4.3->ipython->labquiz==0.8.6) (0.7.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from cryptography->labquiz==0.8.6) (2.0.0)
Requirement already satisfied: pycparser in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from cffi>=2.0.0->cryptography->labquiz==0.8.6) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from pandas->labquiz==0.8.6) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from pandas->labquiz==0.8.6) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from pandas->labquiz==0.8.6) (2025.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->labquiz==0.8.6) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from requests->labquiz==0.8.6) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from requests->labquiz==0.8.6) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from requests->labquiz==0.8.6) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from requests->labquiz==0.8.6) (2026.2.25)
Requirement already satisfied: executing>=1.2.0 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from stack-data->ipython->labquiz==0.8.6) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from stack-data->ipython->labquiz==0.8.6) (3.0.1)
Requirement already satisfied: pure-eval in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from stack-data->ipython->labquiz==0.8.6) (0.2.3)
Building wheels for collected packages: labquiz
  Building wheel for labquiz (pyproject.toml) ... done
  Created wheel for labquiz: filename=labquiz-0.8.6-py3-none-any.whl size=82435 sha256=56da24a820eaa587e29219bf5c3c56a5bda484dc646dc67e1d0251d3471bffe2
  Stored in directory: /private/var/folders/y4/_fmvp6f90fz8qzbxtlfl6pwr0000gn/T/pip-ephem-wheel-cache-_lacsav7/wheels/1e/4c/d9/db884094322e2fc85615023964c74cad1b36086588b8643b01
Successfully built labquiz
WARNING: Error parsing dependencies of mystmd: [Errno 2] No such file or directory: '/opt/anaconda3/envs/jlab/lib/python3.9/site-packages/mystmd-1.7.0.dist-info/METADATA'
Installing collected packages: labquiz
  Attempting uninstall: labquiz
    Found existing installation: labquiz 0.8.8
    Uninstalling labquiz-0.8.8:
      Successfully uninstalled labquiz-0.8.8
Successfully installed labquiz-0.8.6
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install -e ..

Obtaining file:///Users/bercherj/JFB/dev/labquizdev
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: ipywidgets>=7.6.5 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.8) (8.1.8)
Requirement already satisfied: pyyaml in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.8) (6.0.3)
Requirement already satisfied: cryptography in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.8) (46.0.5)
Requirement already satisfied: ipython in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.8) (8.18.1)
Requirement already satisfied: numpy in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.8) (2.0.2)
Requirement already satisfied: pandas in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.8) (2.3.3)
Requirement already satisfied: requests in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from labquiz==0.8.8) (2.32.5)
Requirement already satisfied: comm>=0.1.3 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets>=7.6.5->labquiz==0.8.8) (0.2.3)
Requirement already satisfied: traitlets>=4.3.1 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets>=7.6.5->labquiz==0.8.8) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets>=7.6.5->labquiz==0.8.8) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipywidgets>=7.6.5->labquiz==0.8.8) (3.0.16)
Requirement already satisfied: decorator in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.8) (5.2.1)
Requirement already satisfied: jedi>=0.16 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.8) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.8) (0.2.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.8) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.8) (2.19.2)
Requirement already satisfied: stack-data in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.8) (0.6.3)
Requirement already satisfied: typing-extensions in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.8) (4.15.0)
Requirement already satisfied: exceptiongroup in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.8) (1.3.1)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from ipython->labquiz==0.8.8) (4.9.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->labquiz==0.8.8) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from jedi>=0.16->ipython->labquiz==0.8.8) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from pexpect>4.3->ipython->labquiz==0.8.8) (0.7.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from cryptography->labquiz==0.8.8) (2.0.0)
Requirement already satisfied: pycparser in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from cffi>=2.0.0->cryptography->labquiz==0.8.8) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from pandas->labquiz==0.8.8) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from pandas->labquiz==0.8.8) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from pandas->labquiz==0.8.8) (2025.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->labquiz==0.8.8) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from requests->labquiz==0.8.8) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from requests->labquiz==0.8.8) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from requests->labquiz==0.8.8) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from requests->labquiz==0.8.8) (2026.2.25)
Requirement already satisfied: executing>=1.2.0 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from stack-data->ipython->labquiz==0.8.8) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from stack-data->ipython->labquiz==0.8.8) (3.0.1)
Requirement already satisfied: pure-eval in /opt/anaconda3/envs/jlab/lib/python3.9/site-packages (from stack-data->ipython->labquiz==0.8.8) (0.2.3)
Building wheels for collected packages: labquiz
  Building editable for labquiz (pyproject.toml) ... done
  Created wheel for labquiz: filename=labquiz-0.8.8-0.editable-py3-none-any.whl size=13745 sha256=41ddf0c544458cb14471b3cde05d7f81d348b4e92d9ba47fafd22dc0c4aa0a11
  Stored in directory: /private/var/folders/y4/_fmvp6f90fz8qzbxtlfl6pwr0000gn/T/pip-ephem-wheel-cache-xywugcmd/wheels/d1/a4/6a/2d0455edac8bd2903aa7d37748fff8a59c1af9f0d5b7ceb39c
Successfully built labquiz
WARNING: Error parsing dependencies of mystmd: [Errno 2] No such file or directory: '/opt/anaconda3/envs/jlab/lib/python3.9/site-packages/mystmd-1.7.0.dist-info/METADATA'
Installing collected packages: labquiz
  Attempting uninstall: labquiz
    Found existing installation: labquiz 0.8.8
    Uninstalling labquiz-0.8.8:
      Successfully uninstalled labquiz-0.8.8
Successfully installed labquiz-0.8.8
Note: you may need to restart the kernel to use updated packages.

In [5]:
import labquiz
from labquiz import QuizLab
labquiz.set_language('en')

#URL without sheetID - Here we are in stand-alone mode, no internet connection required, results not saved
URL = ""
QUIZFILE = "test.yaml"  
quiz = QuizLab(URL, QUIZFILE, needAuthentification=True, retries=99)                        # no authentification, 100 attempts allowed

VBox(children=(HTML(value="<h2 style='margin-top: 0; margin-bottom: 0; line-height: 1.2;'> Enter your first na…

LabQuiz, labquiz version 0.8.8
--> Restarting the quiz under a new name...

In [40]:
quiz.quiz_bank['quiz63']

{'type': 'mcq-template',
 'question': 'What is the derivative of $x^n$, with n={n}, that is  $x^{n}$,',
 'propositions': [{'proposition': 'The derivative is ${n} x^{n-1}$',
   'expected': 'True',
   'label': 'correct_derivative',
   'answer': '',
   'tip': ''},
  {'label': 'wrong',
   'proposition': 'The derivative is $\\frac{1}{n} x^{n}$',
   'expected': 'False',
   'answer': '',
   'tip': ''},
  {'label': 'wrong2',
   'proposition': 'The derivative is $\\frac 1{n-1} x^{n-1}$',
   'expected': 'False',
   'answer': '',
   'tip': ''},
  {'label': 'wrong3',
   'proposition': 'The derivative is ${n-1} x^{n-1}$',
   'expected': 'False',
   'answer': '',
   'tip': ''}],
 'label': 'q:quiz63',
 'variables': {'n': {'type': 'int',
   'structure': 'scalar',
   'engine': 'numpy rng.',
   'call': 'integers(0, 10)'}}}

In [23]:
quiz.quiz_bank['quiz63']['question'] = 'What is the derivative of $x^n$, with n={n}, that is  $x^{n}$, '

In [41]:
quiz.quiz_correct['quiz63'] = 0
quiz.show('quiz63', autovars=True)

VBox(children=(HTML(value='<style>.correct { color:#008000; font-weight:bold; margin:4px 0; }.wrong { color:#b…

(examples_of_quizzes)=
# Some examples of quizzes

## Standard MCQ

In [44]:
quiz.show('quiz2')

VBox(children=(HTML(value='<style>.correct { color:#008000; font-weight:bold; margin:4px 0; }.wrong { color:#b…

In [42]:
quiz.show('quiz5')

VBox(children=(HTML(value='<style>.correct { color:#008000; font-weight:bold; margin:4px 0; }.wrong { color:#b…

## Numerical values

In [7]:
quiz.quiz_correct['quiz54'] = 0
quiz.set_test_mode(False)
quiz.show('quiz54', autovars=True)

VBox(children=(HTML(value='<style>.correct { color:#008000; font-weight:bold; margin:4px 0; }.wrong { color:#b…

In [46]:
quiz.quiz_correct['quiz59'] = 0

In [50]:
quiz.show('quiz59')  # A quiz with numeric answers - answers are 0 et 1

VBox(children=(HTML(value='<style>.correct { color:#008000; font-weight:bold; margin:4px 0; }.wrong { color:#b…

In [3]:
quiz.quiz_correct['quiz53'] = 0
quiz.quiz_correct['quiz54'] = 0

## Values ​​passed as parameters; type "mcq-template"

In [7]:
# A test with values passed as parameters; type "mcq-template"
a = 2
b = 7
quiz.show('quiz53', A=a, B=b)

VBox(children=(HTML(value='<style>.correct { color:#008000; font-weight:bold; margin:4px 0; }.wrong { color:#b…

In [9]:
# A test with values passed as parameters; type "mcq-template"
# autovars=True --> Generate values on the fly
quiz.show('quiz53', autovars=True)

VBox(children=(HTML(value='<style>.correct { color:#008000; font-weight:bold; margin:4px 0; }.wrong { color:#b…

## Test mode

In [10]:
# A test with values passed as parameters; type "numeric-template"
# and switching to test mode (no correction)
quiz.set_test_mode()
a = 2
b = 11
quiz.show('quiz54', a=a, b=b)

VBox(children=(HTML(value='<style>.correct { color:#008000; font-weight:bold; margin:4px 0; }.wrong { color:#b…

## Exam mode

In [18]:
quiz.set_exam_mode()
quiz.show('quiz3')

VBox(children=(HTML(value='<style>.correct { color:#008000; font-weight:bold; margin:4px 0; }.wrong { color:#b…

In [41]:
quiz.set_normal_mode()

In [49]:
1.72333**2.0

2.9698662889

## MCQ with logical constraints in the answers

In [19]:
quiz.set_normal_mode()
quiz.show('quiz57')

VBox(children=(HTML(value='<style>.correct { color:#008000; font-weight:bold; margin:4px 0; }.wrong { color:#b…

# Saving answers in a google-sheet

A demo Google Sheet was created following the instructions given in the doc, section 8. 

It is shared for reading here, and you will therefore be able to see the changes being made there as they go.
https://docs.google.com/spreadsheets/d/1lBh-BPZN2C6kt2xRvWfviZkyzIYl2_G9vbIji19lTsA/edit?usp=sharing

The deployment address is:
https://script.google.com/macros/s/AKfycby49Z5kU9tcs49p_LDHxDg2z-4l7hZKlA2pYC4C6Zj_Tp4PD8WNvjN774Lj5qlqoQopRQ/exec
This is the one we will specify for data collection.

```{warning} Restart
At this level, you need to restart the kernel, by pressing the `Restart the Kernel` button in the menu bar, or via the Kernel/Restart Kernel menu. Indeed, in the event of a simple relaunch of a new quiz based on the same QUIZFILE question file, the parameters and previous answers are restored (this is to prevent a student from giving himself additional attempts simply by relaunching the quiz, or from answering for several classmates); even if all this would be detectable in the logs. 
```

In [ ]:
LABQUIZ_LAST_VERSION = "0.7.9.1"
labquiz_url = f"https://perso.esiee.fr/~bercherj/JliteNotes/pypi/labquiz-{LABQUIZ_LAST_VERSION}-py3-none-any.whl"
import sys
if sys.platform == "emscripten":   #Jupyterlite
    import micropip
    import js
    from jfb_jlite_init import get_base_url, setup_env, update_files
    import pyodide_http
    base_url = get_base_url()
    toinstall = [labquiz_url, 'requests', 'ipywidgets', 'cryptography', 'pandas', 'statsmodels']
    print(f"📍 Serveur détecté : {base_url}")
    print(f"📦 Cible : {labquiz_url}")
    print("💡 Installation of required packages")
    print("   --------------------------------")
    await setup_env(base_url, toinstall)
    print("\n💡 Udating data files")
    await update_files(toinstall)
else:
# Latest version can be found in https://github.com/jfbercher/labquiz/releases    print("💡 Installation of required packages (classical Python)")
# Put them here...    print(f"👉 Installing labquiz package, version: {LABQUIZ_LAST_VERSION}...")
    %pip install "https://perso.esiee.fr/~bercherj/JliteNotes/pypi/labquiz-{LABQUIZ_LAST_VERSION}-py3-none-any.whl" --upgrade -qq
    print("✅ Successful install.")

In [ ]:
import labquiz
from labquiz import QuizLab

#Connected mode URL, saved results
URL = "https://script.google.com/macros/s/AKfycby49Z5kU9tcs49p_LDHxDg2z-4l7hZKlA2pYC4C6Zj_Tp4PD8WNvjN774Lj5qlqoQopRQ/exec"
QUIZFILE = "test.yaml"  # Le fichier utilisé dans la doc
quiz = QuizLab(URL, 
               QUIZFILE, 
               needAuthentification=True,  # On demande une authentification
               retries=2)                  # 3 essais permis
# by default, exam_mode and test_mode are False

NB - *If you restart a quiz with the same question file, by changing the user name for example, the previous results (number of attempts in particular are restored); this does not reset.*

## Take the quizzes

You may have already seen lines appear in the Google-sheet, even before authentication. The machine identifier `notebook_id` has been calculated and noted. 

👉🏼 **We will now resume the quizzes from the previous section ⬆️ [](examples_of_quizzes), copied below to make it more practical,**
Then, you can continue on to the following sections.

- nothing stops you from testing until you have reached the maximum allowed or the grade you want
- you will note (and this is the objective!) that the entries are recorded in the Google sheet, as well as the operating parameters (exam mode, test, number of attempts, corrections requested), as well as the answers to each question

Therefore, we can very well 
- control the parameters used, 
- and correct

We will see that in the following.

### Standard MCQ

In [ ]:
quiz.show('quiz1')

In [ ]:
quiz.show('quiz5')

### Numeric values

In [ ]:
quiz.show('quiz59')  # A quiz with numeric answers - answers are 0 and 1

### Values ​​passed as parameters; type "mcq-template"

In [10]:
# A test with values ​​passed as parameters; type "mcq-template"
a = 2
b = 7
quiz.show('quiz53', A=a, B=b)

VBox(children=(HTML(value='<style>.correct { color:#008000; font-weight:bold; margin:4px 0; }.wrong { color:#b…

### Test mode

In [ ]:
# A test with values ​​passed as parameters; type "numeric-template"
# and switching to test mode (no correction)
quiz.set_test_mode()
a = 2
b = 11
quiz.show('quiz54', a=a, b=b)

### Exam mode

In [ ]:
# Neither correction nor tips
quiz.set_exam_mode(True)
quiz.show('quiz58')

### MCQ with logical constraints in the answers

In [ ]:
quiz.set_exam_mode(False)
quiz.show('quiz57')

## Parameter control

We copy here the snippet given in the doc

In [13]:
from labquiz.putils import readData, getAllStudentsAnsvers, correctAll

## 1 – Reading data
URL = "https://script.google.com/macros/s/AKfycby49Z5kU9tcs49p_LDHxDg2z-4l7hZKlA2pYC4C6Zj_Tp4PD8WNvjN774Lj5qlqoQopRQ/exec"
SECRET = "Code_demo$!"
data, data_filt = readData(URL, SECRET)

## 2 – Students
students = sorted(list(data["student"].dropna().unique()))

## 3 - imports
from labquiz.putils import  check_integrity_all_std, check_start_integrity_all_std, check_hash_integrity

## 4 - test
originalp = {'retries':2, 'exam_mode':False, 'test_mode':False}
starting_values = {'exam_mode':False, 'retries':2 }

print("------------------------")
print("==> test start_integrity")
print("------------------------")
check_start_integrity_all_std(starting_values, data)
print("--------------------------------")
print("==> test check_integrity_all_std")
print("--------------------------------")
check_integrity_all_std(originalp, students, data)

------------------------
==> test start_integrity
------------------------
6babf35c589a9919 - record 64 : original key 'exam_mode' modified from False into True
6babf35c589a9919 - record 64 : original key 'retries' modified from 2 into 99
888ca76b35a43964 - record 8 : original key 'exam_mode' modified from False into True
888ca76b35a43964 - record 8 : original key 'retries' modified from 2 into 99
888ca76b35a43964 - record 16 : original key 'exam_mode' modified from False into True
888ca76b35a43964 - record 16 : original key 'retries' modified from 2 into 99
888ca76b35a43964 - record 19 : original key 'exam_mode' modified from False into True
888ca76b35a43964 - record 19 : original key 'retries' modified from 2 into 99
888ca76b35a43964 - record 29 : original key 'exam_mode' modified from False into True
888ca76b35a43964 - record 29 : original key 'retries' modified from 2 into 99
--------------------------------
==> test check_integrity_all_std
--------------------------------
Beaugars René - record 30 :
      - Original key 'retries' modified from 2 to 99
      - Original key 'exam_mode' modified from False to True
Bouchon Loic - record 61 :
      - Original key 'test_mode' modified from False to True
Bouchon Loic - record 62 :
      - Original key 'exam_mode' modified from False to True
Dupont Jules - record 21 :
      - Original key 'retries' modified from 2 to 99
      - Original key 'exam_mode' modified from False to True
Dupont Jules - record 23 :
      - Original key 'retries' modified from 2 to 99
      - Original key 'exam_mode' modified from False to True
Dupont Jules - record 25 :
      - Original key 'retries' modified from 2 to 99
      - Original key 'exam_mode' modified from False to True
Dupont Jules - record 27 :
      - Original key 'retries' modified from 2 to 99
Dupont Paul - record 4 :
      - Original key 'test_mode' modified from False to True
Dupont Paul - record 5 :
      - Original key 'retries' modified from 2 to 100
      - Original key 'exam_mode' modified from False to True
Dupont Paul - record 6 :
      - Original key 'exam_mode' modified from False to True
Dupont Paul - record 7 :
      - Original key 'exam_mode' modified from False to True
Durand Jules - record 20 :
      - Original key 'retries' modified from 2 to 99
      - Original key 'exam_mode' modified from False to True
Durand Jules - record 22 :
      - Original key 'retries' modified from 2 to 99
      - Original key 'exam_mode' modified from False to True
Durand Jules - record 24 :
      - Original key 'retries' modified from 2 to 99
      - Original key 'exam_mode' modified from False to True
Durand Jules - record 26 :
      - Original key 'retries' modified from 2 to 99
      - Original key 'exam_mode' modified from False to True
GROMOV Wladimir - record 34 :
      - Original key 'retries' modified from 2 to
      - Original key 'exam_mode' modified from False to
      - Original key 'test_mode' modified from False to
GROMOV Wladimir - record 35 :
      - Original key 'retries' modified from 2 to
      - Original key 'exam_mode' modified from False to
      - Original key 'test_mode' modified from False to
GROMOV Wladimir - record 36 :
      - Original key 'retries' modified from 2 to
      - Original key 'exam_mode' modified from False to
      - Original key 'test_mode' modified from False to
GROMOV Wladimir - record 37 :
      - Original key 'retries' modified from 2 to
      - Original key 'exam_mode' modified from False to
      - Original key 'test_mode' modified from False to
Morane Bob - record 41 :
      - Original key 'test_mode' modified from False to True
Morane Bob - record 42 :
      - Original key 'exam_mode' modified from False to True
Morin Juliette - record 46 :
      - Original key 'retries' modified from 2 to 99
Morin Juliette - record 47 :
      - Original key 'retries' modified from 2 to 99
Morin Juliette - record 48 :
      - Original key 'retries' modified from 2 to 99
Morin Juliette - record 49 :
      - Original key 'retries' modified from 2 to 99
Morin Juliette - record 50 :
      - Original key 'retries' modified from 2 to 99
      - Original key 'test_mode' modified from False to True
Morin Juliette - record 51 :
      - Original key 'retries' modified from 2 to 99
      - Original key 'exam_mode' modified from False to True
Morin Juliette - record 52 :
      - Original key 'retries' modified from 2 to 99
TEST John - record 65 :
      - Original key 'retries' modified from 2 to
      - Original key 'exam_mode' modified from False to
      - Original key 'test_mode' modified from False to
TEST Marcus - record 66 :
      - Original key 'retries' modified from 2 to
      - Original key 'exam_mode' modified from False to
      - Original key 'test_mode' modified from False to
Turk Mark - record 14 :
      - Original key 'test_mode' modified from False to True
Turk Mark - record 15 :
      - Original key 'test_mode' modified from False to True

## Fix

In [17]:
from labquiz.putils import correctQuizzes

# Commented here because already specified above
#URL = "https://URL_UTILISÉE_FOUR_RECUEILLIR_LES_RESULTATS"
#SECRET = “SECRET_PASSWORD_SPECIFIED_IN_THE_SHEET”
#QUIZFILE = "NAME_DU_FICHIER_DE_QUESTIONS.yml" #quiz file CONTAINING the expected values
Res = correctQuizzes(URL, SECRET, QUIZFILE)
Res

LabQuiz, labquiz version 0.8.8
--> Restarting the quiz under a new name...
Error correcting student TEST John, quiz_id=quiz62

,quiz1,quiz2,quiz3,quiz4,quiz5,quiz6,quiz53,quiz54,quiz57,quiz58,quiz59,quiz62,maxpts,Note
Beaugars René,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.00,0.0,0.0,0.0,26.0,0.769231
Bouchon Loic,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.00,1.0,1.0,0.0,26.0,5.384615
Dupont Paul,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1.0,0.0,0.0,26.0,1.538462
GROMOV Wladimir,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,26.0,0.769231
Morane Bob,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.00,0.0,0.5,0.0,26.0,1.923077
Morin Juliette,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.00,1.0,1.0,0.0,26.0,5.384615
TEST John,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,26.0,0.000000
TEST Marcus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,26.0,0.000000
Turk Mark,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.25,0.0,0.0,0.0,26.0,1.730769

> Note: In this mode, the correction is calculated on all the questions in the file. If you only want to answer a few questions, cancel the excess questions via a scale. Also columns with no answers at all are not displayed.

In [18]:
# Construction of the new scale - 1 for the questions answered, zero otherwise
scale1 = {key:1 for key in Res.columns}
scale = {key:0 for key in quiz.quiz_bank.keys() if key not in Res.columns}
scale.update(scale1)
Res = correctQuizzes(URL, SECRET, QUIZFILE, bareme=scale)
Res

LabQuiz, labquiz version 0.8.8
--> Restarting the quiz under a new name...
Error correcting student TEST John, quiz_id=quiz62

,quiz1,quiz2,quiz3,quiz4,quiz5,quiz6,quiz53,quiz54,quiz57,quiz58,quiz59,quiz62,maxpts,Note
Beaugars René,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.00,0.0,0.0,0.0,12.0,1.666667
Bouchon Loic,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.00,1.0,1.0,0.0,12.0,11.666667
Dupont Paul,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1.0,0.0,0.0,12.0,3.333333
GROMOV Wladimir,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,12.0,1.666667
Morane Bob,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.00,0.0,0.5,0.0,12.0,4.166667
Morin Juliette,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.00,1.0,1.0,0.0,12.0,11.666667
TEST John,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,12.0,0.000000
TEST Marcus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,12.0,0.000000
Turk Mark,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.25,0.0,0.0,0.0,12.0,3.750000

# Using `quiz_dash`

Instead of the command line, you can use the application developed specifically and available here:

https://jfb-quizdash.streamlit.app/

- In the navigation menu, enter the expected parameters: 
URL, SECRET and upload the question file containing the answers (here our "test.yaml")

- In the parameters to monitor, enter `{'retries':2, 'exam_mode':False, 'test_mode':False}` 
which are the parameters that we have set. Any changes to these settings will be reported. 

- Set the number of authorized attempts to 3 (retries +1). 

👉🏼 You can then consult the anomalies in `Integrity live`, the results of the participants in `Monitoring` and finally calculate the results in the `Correction and Notes` tab 😊. 


>Note: *The calculation of the final mark is carried out *only* on quizzes to which at least one answer has been included in the results table. It’s a choice that was made. If you want to use questions that students haven't answered, create a virtual user (you) who will answer all the questions -- or I'll add an option one day, but oh well.*

# Using `quiz_editor` - creating an encrypted version, an exam version

You can modify the question file by hand, but the easiest way is to use the dedicated application. Go to 

https://jfb-quizeditor.streamlit.app/

and upload the file we used `quizzes_basic_filtering_test.yaml` (Start by saving this one on your disk: go to the file manager on the left or `View/File Browser` menu, select the YAML, and `File/Download`)

- From then on, you can edit, add or delete questions. Play with this. 

- In the `quiz_editor` navigation bar, on the left, go down to `Export`. Select a few quizzes (you can also check "Export" on the right while browsing them), then choose `Extract YAML` in the format and click on configure and export. Choose `Encrypted YAML`, a file name, and enter `Wrktz` as password (this is the password that is configured in the Config page of the Google sheet (but as I only shared it with you in reading mode, you should not be able to change it). You can then download the full but encrypted version, and the ``questions only'' version which you could use in exam mode. Let's say that you have saved under the names `export_crypt.yaml` and `export_qo_crypt.yaml` (just specify `export` in `quiz_editor`, suffixes and extensions are added automatically).

All we have to do now is test this (after copying the files to your working directory, or uploading them to Jupyterlite using drag and drop).

In [ ]:
import labquiz
from labquiz import QuizLab

#Connected mode URL, saved results
URL = "https://script.google.com/macros/s/AKfycby49Z5kU9tcs49p_LDHxDg2z-4l7hZKlA2pYC4C6Zj_Tp4PD8WNvjN774Lj5qlqoQopRQ/exec"
QUIZFILE = "export_crypt.yaml"  
quiz = QuizLab(URL, 
               QUIZFILE, 
               needAuthentification=True,  # We ask for authentification
               mandatoryInternet=True,     # Internet required to decrypt quiz file
               exam_mode = True,           # Exam mode
               retries=99)                 # 100 attempts allowed, why not?

In [ ]:
quiz.show("quiz4")

And with the “questions only” file:

In [ ]:
import labquiz
from labquiz import QuizLab

#Connected mode URL, saved results
URL = "https://script.google.com/macros/s/AKfycby49Z5kU9tcs49p_LDHxDg2z-4l7hZKlA2pYC4C6Zj_Tp4PD8WNvjN774Lj5qlqoQopRQ/exec"
QUIZFILE = "export_qo_crypt.yaml"  
quiz = QuizLab(URL, 
               QUIZFILE, 
               needAuthentification=True,  # We ask for authentification
               mandatoryInternet=True,     # Internet required to decrypt quiz file
               exam_mode = True,           # Exam mode
               retries=99)                 # 100 attempts allowed, why not?

In [ ]:
quiz.show("quiz4")